/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken?: string;
                            refreshToken?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh the access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search assets (ticker autocomplete) */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by ticker or name */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of assets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example ITSA4 */
                    ticker: components["parameters"]["TickerParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{ticker}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fundamental indicators, markers, and target prices
         * @description Computes P/E, P/B, DY, ROE (with marker color) and ceiling price (Bazin) / fair price (Graham).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example ITSA4 */
                    ticker: components["parameters"]["TickerParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset indicators */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetIndicators"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{ticker}/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical price series */
        get: {
            parameters: {
                query?: {
                    from?: components["parameters"]["FromParam"];
                    to?: components["parameters"]["ToParam"];
                };
                header?: never;
                path: {
                    /** @example ITSA4 */
                    ticker: components["parameters"]["TickerParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historical series */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricePoint"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions */
        get: {
            parameters: {
                query?: {
                    ticker?: string;
                    from?: components["parameters"]["FromParam"];
                    to?: components["parameters"]["ToParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Record a transaction (buy or sell)
         * @description Entries dated in the past trigger the recalculation engine (docs/business-rules.md §2) asynchronously. The response includes `recalculating: true` while processing runs in the background.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionInput"];
                };
            };
            responses: {
                /** @description Transaction created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Sell larger than the position available on that date */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Transaction detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Remove a transaction (triggers recalculation) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Edit a transaction (triggers recalculation) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionInput"];
                };
            };
            responses: {
                /** @description Transaction updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current portfolio positions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of positions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Position"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio summary (used on the dashboard) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortfolioSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical portfolio value series (growth chart) */
        get: {
            parameters: {
                query?: {
                    from?: components["parameters"]["FromParam"];
                    to?: components["parameters"]["ToParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Daily snapshots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortfolioSnapshot"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/growth-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Growth breakdown (contributions vs. appreciation vs. reinvested dividends) */
        get: {
            parameters: {
                query?: {
                    from?: components["parameters"]["FromParam"];
                    to?: components["parameters"]["ToParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Breakdown for the period */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GrowthBreakdown"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dividends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dividends (history and schedule) — feeds the calendar */
        get: {
            parameters: {
                query?: {
                    from?: components["parameters"]["FromParam"];
                    to?: components["parameters"]["ToParam"];
                    status?: "announced" | "paid" | "pending_review";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of dividends */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dividend"][];
                    };
                };
            };
        };
        put?: never;
        /** Manually register an announced dividend */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DividendInput"];
                };
            };
            responses: {
                /** @description Dividend created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dividend"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dividends/reinvestment-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dividend balance available for reinvestment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: double */
                            availableBalance?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dividends/reinvest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reinvest the dividend balance
         * @description Uses the available balance as the contribution amount in the rebalancing simulator (docs/business-rules.md §3 and §9).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggested purchases generated from the dividend balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RebalanceSuggestion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current allocation targets (by category and by asset) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Targets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationTargets"];
                    };
                };
            };
        };
        /** Set allocation targets */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AllocationTargets"];
                };
            };
            responses: {
                /** @description Targets updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllocationTargets"];
                    };
                };
                /** @description Category percentages don't add up to 100% */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allocation-targets/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate a contribution according to the allocation targets */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: double
                         * @example 5000
                         */
                        contributionAmount: number;
                    };
                };
            };
            responses: {
                /** @description Suggested purchases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RebalanceSuggestion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corporate-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Applied corporate actions (split, reverse split, bonus shares, subscription rights)
         * @description Read-only — populated automatically by the B3 statement import.
         */
        get: {
            parameters: {
                query?: {
                    ticker?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorporateAction"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/b3-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a B3 statement of transactions */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Import result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
                /** @description Invalid file or unrecognized format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example SELL_EXCEEDS_POSITION */
            code?: string;
            message?: string;
        };
        /** @enum {string} */
        AssetCategory: "stock" | "reit" | "fixed_income" | "crypto";
        Asset: {
            /** @example ITSA4 */
            ticker?: string;
            /** @example Itaúsa */
            name?: string;
            category?: components["schemas"]["AssetCategory"];
            /** @description Comes from the quote provider when available; otherwise the UI falls back to an initials avatar colored by category. */
            logoUrl?: string | null;
        };
        PricePoint: {
            /** Format: date */
            date?: string;
            /** Format: double */
            price?: number;
        };
        /** @enum {string} */
        IndicatorMarker: "green" | "yellow" | "red";
        Indicator: {
            /** @example P/B */
            name?: string;
            /** Format: double */
            value?: number;
            marker?: components["schemas"]["IndicatorMarker"];
            /** @description Text shown in the explanatory tooltip. */
            description?: string;
        };
        AssetIndicators: {
            ticker?: string;
            indicators?: components["schemas"]["Indicator"][];
            /** Format: double */
            bazinCeilingPrice?: number | null;
            /** Format: double */
            grahamFairPrice?: number | null;
        };
        /** @enum {string} */
        TransactionType: "buy" | "sell";
        TransactionInput: {
            /** @example ITSA4 */
            ticker: string;
            type: components["schemas"]["TransactionType"];
            /** @example 100 */
            quantity: number;
            /**
             * Format: double
             * @example 9.1
             */
            pricePerShare: number;
            /** Format: date */
            date: string;
            /**
             * Format: double
             * @description Optional — brokerage/exchange fees, used only for cost precision, not required.
             */
            fees?: number | null;
        };
        Transaction: components["schemas"]["TransactionInput"] & {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            source?: "manual" | "b3_import";
            /** @description true while the recalculation engine is still processing this change. */
            recalculating?: boolean;
        };
        Position: {
            ticker?: string;
            category?: components["schemas"]["AssetCategory"];
            quantity?: number;
            /** Format: double */
            averagePrice?: number;
            /** Format: double */
            currentPrice?: number;
            /** Format: double */
            profitPercentage?: number;
            /** Format: double */
            portfolioPercentage?: number;
        };
        PortfolioSummary: {
            /** Format: double */
            totalValue?: number;
            /** Format: double */
            todayChangePercentage?: number;
            /** Format: double */
            monthProfitPercentage?: number;
            /** Format: double */
            monthDividends?: number;
            /** Format: double */
            averageDy?: number;
            assetCount?: number;
        };
        PortfolioSnapshot: {
            /** Format: date */
            date?: string;
            /** Format: double */
            totalValue?: number;
            valueByCategory?: {
                [key: string]: number;
            };
            /** Format: double */
            cumulativeContributions?: number;
            /** Format: double */
            cumulativeReinvestedDividends?: number;
        };
        /** @description contributions + appreciation + reinvestedDividends must add up to totalChange (computed by residual, docs/business-rules.md §8). */
        GrowthBreakdown: {
            /** Format: double */
            totalChange?: number;
            /** Format: double */
            contributions?: number;
            /** Format: double */
            appreciation?: number;
            /** Format: double */
            reinvestedDividends?: number;
        };
        /** @enum {string} */
        DividendType: "dividend" | "jcp" | "reit_income" | "fixed_income_redemption";
        DividendInput: {
            ticker: string;
            type: components["schemas"]["DividendType"];
            /** Format: double */
            grossValuePerShare: number;
            /** Format: date */
            exDate: string;
            /** Format: date */
            paymentDate: string;
        };
        Dividend: components["schemas"]["DividendInput"] & {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            withholdingTaxRate?: number;
            /** Format: double */
            netValuePerShare?: number;
            /** @enum {string} */
            status?: "announced" | "paid" | "pending_review";
            reinvested?: boolean;
        };
        RebalanceItem: {
            ticker?: string;
            /** Format: double */
            currentPercentage?: number;
            /** Format: double */
            targetPercentage?: number;
            /** Format: double */
            suggestedValue?: number;
            suggestedQuantity?: number;
        };
        RebalanceSuggestion: {
            /** Format: double */
            contributionAmount?: number;
            items?: components["schemas"]["RebalanceItem"][];
            /**
             * Format: double
             * @description Rounding leftover not allocated in this contribution.
             */
            unallocatedValue?: number;
        };
        TargetAsset: {
            ticker?: string;
            /**
             * Format: double
             * @description Null = split equally among the assets in the same category.
             */
            weightInCategory?: number | null;
        };
        AllocationTarget: {
            category?: components["schemas"]["AssetCategory"];
            /** Format: double */
            percentage?: number;
            assets?: components["schemas"]["TargetAsset"][];
        };
        AllocationTargets: {
            targets?: components["schemas"]["AllocationTarget"][];
        };
        /** @enum {string} */
        CorporateActionType: "split" | "reverse_split" | "bonus_shares" | "subscription_rights";
        CorporateAction: {
            /** Format: uuid */
            id?: string;
            ticker?: string;
            type?: components["schemas"]["CorporateActionType"];
            /** Format: date */
            date?: string;
            /** Format: double */
            factor?: number;
            /** @enum {string} */
            source?: "b3_import";
        };
        ImportResult: {
            transactionsCreated?: number;
            dividendsCreated?: number;
            corporateActionsCreated?: number;
            duplicatesSkipped?: number;
            rowsForManualReview?: {
                row?: number;
                reason?: string;
            }[];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authenticated */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example ITSA4 */
        TickerParam: string;
        FromParam: string;
        ToParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
