"""create assets, transactions, positions

Revision ID: 4b95abc8070b
Revises: 
Create Date: 2026-08-20 19:17:44.655222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b95abc8070b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('stock', 'reit', 'fixed_income', 'crypto', name='asset_category', native_enum=False, length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('positions',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('buy', 'sell', name='transaction_type', native_enum=False, length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.Enum('manual', 'b3_import', name='transaction_source', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_ticker'), 'transactions', ['ticker'], unique=False)
    # ### end Alembic commands ###

    # Starter asset catalog so autocomplete and the unknown-ticker sanity check are
    # usable before the quote provider (Sprint 3) enriches/expands it.
    assets_table = sa.table(
        'assets',
        sa.column('ticker', sa.String),
        sa.column('name', sa.String),
        sa.column('category', sa.String),
        sa.column('logo_url', sa.String),
    )
    op.bulk_insert(assets_table, [
        {'ticker': 'ITSA4', 'name': 'Itaúsa PN', 'category': 'stock', 'logo_url': None},
        {'ticker': 'ITUB4', 'name': 'Itaú Unibanco PN', 'category': 'stock', 'logo_url': None},
        {'ticker': 'PETR4', 'name': 'Petrobras PN', 'category': 'stock', 'logo_url': None},
        {'ticker': 'VALE3', 'name': 'Vale ON', 'category': 'stock', 'logo_url': None},
        {'ticker': 'BBAS3', 'name': 'Banco do Brasil ON', 'category': 'stock', 'logo_url': None},
        {'ticker': 'BBDC4', 'name': 'Bradesco PN', 'category': 'stock', 'logo_url': None},
        {'ticker': 'WEGE3', 'name': 'WEG ON', 'category': 'stock', 'logo_url': None},
        {'ticker': 'TAEE11', 'name': 'Taesa UNT', 'category': 'stock', 'logo_url': None},
        {'ticker': 'BBSE3', 'name': 'BB Seguridade ON', 'category': 'stock', 'logo_url': None},
        {'ticker': 'SAPR11', 'name': 'Sanepar UNT', 'category': 'stock', 'logo_url': None},
        {'ticker': 'MXRF11', 'name': 'Maxi Renda FII', 'category': 'reit', 'logo_url': None},
        {'ticker': 'HGLG11', 'name': 'CSHG Logística FII', 'category': 'reit', 'logo_url': None},
        {'ticker': 'KNRI11', 'name': 'Kinea Renda Imobiliária FII', 'category': 'reit', 'logo_url': None},
        {'ticker': 'XPML11', 'name': 'XP Malls FII', 'category': 'reit', 'logo_url': None},
        {'ticker': 'VISC11', 'name': 'Vinci Shopping Centers FII', 'category': 'reit', 'logo_url': None},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_ticker'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('positions')
    op.drop_table('assets')
    # ### end Alembic commands ###
