"""add system state, portfolio snapshots, price history

Revision ID: 4e43b7a1df67
Revises: 6efbf9671aae
Create Date: 2026-08-20 19:59:08.014902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e43b7a1df67'
down_revision: Union[str, Sequence[str], None] = '6efbf9671aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('value_by_category', sa.JSON(), nullable=False),
    sa.Column('cumulative_contributions', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cumulative_reinvested_dividends', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('system_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('price_history',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('system_state')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
