"""add dividends, corporate actions, import review rows

Revision ID: 6efbf9671aae
Revises: 4b95abc8070b
Create Date: 2026-08-20 19:33:50.473632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efbf9671aae'
down_revision: Union[str, Sequence[str], None] = '4b95abc8070b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_review_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('raw_content', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('split', 'reverse_split', 'bonus_shares', 'subscription_rights', name='corporate_action_type', native_enum=False, length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.Enum('manual', 'b3_import', name='transaction_source', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_date'), 'corporate_actions', ['date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ticker'), 'corporate_actions', ['ticker'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('type', sa.Enum('dividend', 'jcp', 'reit_income', 'fixed_income_redemption', name='dividend_type', native_enum=False, length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gross_value_per_share', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('withholding_tax_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('net_value_per_share', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('announced', 'paid', 'pending_review', name='dividend_status', native_enum=False, length=20), nullable=False),
    sa.Column('reinvested', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'b3_import', name='transaction_source', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_payment_date'), 'dividends', ['payment_date'], unique=False)
    op.create_index(op.f('ix_dividends_ticker'), 'dividends', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dividends_ticker'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_payment_date'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_corporate_actions_ticker'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_table('import_review_rows')
    # ### end Alembic commands ###
